create table claims
(Billing_provider_claim_status VARCHAR(255),
Client_ID VARCHAR(255),
Claim_Number VARCHAR(255) PRIMARY KEY,
Claims_Group_Number VARCHAR(255),
Contract_ID VARCHAR(255),
Drug_Name VARCHAR(255),
Enrollment_source_Code VARCHAR(255),
Familiy_indivisual_pin_identifier VARCHAR(255),
Line_of_Business VARCHAR(255),
Prescrption_Number VARCHAR(255),
Product_Line_Code VARCHAR(255),
Refill_Number VARCHAR(255),
Blue_Card_Indicator VARCHAR(255),
Claim_Indicator VARCHAR(255),
Coverage_of_Member_code VARCHAR(255),
Diagnosis_Code VARCHAR(255),
Drug_Charge VARCHAR(255),
Members_cost VARCHAR(255),
Plan_Id VARCHAR(255),
Rejection_Code VARCHAR(255),
Payer_Claim_Number VARCHAR(255),
Service_Type VARCHAR(255),
Transaction_ID VARCHAR(255),
Transaction_Pega_Status VARCHAR(255),
Transaction_Type VARCHAR(255),
Claim_Date VARCHAR(255),
Claim_Finalized_Date VARCHAR(255),
Claim_Recieved_Date VARCHAR(255),
Billing_Provider_ID VARCHAR(255),
UMI VARCHAR(255)
);
