CREATE TABLE member
(ActiveCoverageInd VARCHAR(255),
AddressLine1 VARCHAR(255),
AddressLine2 VARCHAR(255),
AddressLine3 VARCHAR(255),
AddressLine4 VARCHAR(255),
AddressTypeCode VARCHAR(255),
AddressTypeCodeDescription VARCHAR(255),
City VARCHAR(50),
CountryName VARCHAR(255),
DateOfBirth VARCHAR(50),
EffectiveDate VARCHAR(50),
EndDate VARCHAR(50),
Extension VARCHAR(255),
FirstName VARCHAR(50),
Group_Number VARCHAR(255),
Group_Number_ICIS VARCHAR(255),
Group_Phone_Number VARCHAR(255),
LastName VARCHAR(50),
MemberID VARCHAR(255),
MiddleName VARCHAR(50),
NamePrefix VARCHAR(50),
NameSuffix VARCHAR(50),
PhoneNumber VARCHAR(255),
PhoneType VARCHAR(255),
SourceSystem VARCHAR(255),
state VARCHAR(20),
TaxID VARCHAR(255),
ZipCode VARCHAR(255),
UMI VARCHAR(255) PRIMARY KEY,
Member_relationship_to_policy_holder VARCHAR(50),
Member_Type VARCHAR(50),
Plan_Indicator VARCHAR(255)
);